### ISSUE TITLE
Any plan for this parser?

### ISSUE THREAD

**Issue by axiangcoding** [nilshellerhoff/warthunder-replay-parser#1]
I am a WT player, and this seems to be a useful tool, any plan for this parser?

**Comment by nilshellerhoff** [comment]
Hi @axiangcoding ,

the problem unfortunately is that the replay format is not documented publicly anyhow and my experience with analyzing binary files is very limited. I intend to clean the code a bit and make it more reusable, but so far there are certain key points which I don't know how to extract from the replay:
- ticket drain
- who won/lost a battle
- chat messages/battle messages
- ...

So the value of this project unfortunately might be very limited.

**Comment by axiangcoding** [comment]
Hi @nilshellerhoff ,

If there is no document describing this type of format, trying to parse it yourself will be a dead end. 
But thank you for trying, perhaps in the future, this project will make critical progress. I look forward to it.
